logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://valslesbianbar.com
media_folder: "static/assets"

backend:
  name: git-gateway
  repo: lydiascarf/valslesbianbar.com
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/175e8c21-a3ac-4802-a40d-416bc84f8689/pkce
  auth_token_endpoint: /sites/175e8c21-a3ac-4802-a40d-416bc84f8689/token
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

collections:
  - label: One off Events
    name: oneoff_events
    folder: "content/events/oneoffs"
    format: yaml
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date and Time", name: "datetime", widget: "datetime"}
      - {label: "Featured Image", name: "flyer", widget: "image", choose_url: false}
      - {label: "Description", name: "description", widget: "markdown"}
  - label: Repeating Events
    name: repeating_events
    folder: "content/events/repeating_templates"
    format: yaml
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "flyer", widget: "image", choose_url: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Repeat"
        name: repeat
        widget: "object"
        fields: 
          - {label: "Interval", name: "interval", widget: "select", options: ['weekly']}
          - label: "First Date and Time"
            name: "datetime"
            widget: "datetime"
            default: "{{now}}"
            date_format: "MM.DD.YYYY"
            time_format: "HH:mm"
